fix: don't validate readOnly properties in request
stoplightio/prism pull request #1619
Opened 2021-01-06 11:25 UTC by marcelltoth

Resolves #1142 

I'm not familiar with prism and FP much so code style, placement and naming might be off. Yet I think it fixes both the issue above, both the related `writeOnly` support.

2021-01-07 10:47 UTC, XVincentX requested changes
I gave it a quick look; this might solve the issue but the implementation is a little bit off.

I am also not 100% sure if this is something that Prism should handle directly or if AJV supports this in some degrees.

I suggest to punt this solution for know and move forward when a full investigation has done.

I've left some comments (mostly for personal purposes)

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/mocker/generator/JSONSchema.ts
> +import { Either, tryCatch, toError, right } from 'fp-ts/Either';
We usually import everything 
```suggestion
import * as E from 'fp-ts/Either';
```

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/mocker/generator/JSONSchema.ts
> +import { pipe } from 'fp-ts/pipeable';
Don't import from pipeable
```suggestion
import { pipe } from 'fp-ts/function';
```

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/mocker/generator/JSONSchema.ts
> +    )
We never fold, we rather propagate the error and handle it on the edges. This should be chained

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/utils/jsonSchema.ts
> +import { pipe } from 'fp-ts/pipeable';
import from function

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/utils/jsonSchema.ts
> +    }
Use `O.fromPredicate`

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/utils/jsonSchema.ts
> +          return pipe(
Incorrect piping

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/utils/jsonSchema.ts
> +            O.toUndefined
folding — this should not happen

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/utils/jsonSchema.ts
> +      O.getOrElse(() => [] as string[])
folding — this should not happen

2021-01-07 10:47 UTC, XVincentX commented on packages/http/src/validator/validators/body.ts
> +      pipe(O.fromNullable(contentResult.content.schema), O.chain(schemaProcessorMap[context]))
Incorrect piping

2021-01-08 13:26 UTC, philsturgeon commented
@XVincentX only OpenAPI has knowledge of "request" or "response", JSON Schema does not. This makes an awkward difference between "OpenAPI tooling" and "JSON Schema tooling".

[openapi-sampler](https://github.com/Redocly/openapi-sampler) supports this nicely:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/67381/104020093-e99cc900-51bc-11eb-9a03-09fda65fcd46.png">

json-schema-faker was not particularly interested in supporting this last time we talked about it:

https://github.com/json-schema-faker/json-schema-faker/issues/289#issuecomment-521951812

Then AJV would also need to have support added. Whilst we could certainly spend some time convincing the authors that this is a good feature, and help them implement it, we might be better off handling it ourselves for now.

It's not that weird if we do it ourselves because we are an "application" and that has been mentioned specifically in the way readOnly/writeOnly work.

> These keywords can be used to assist in user interface instance generation. In particular, an application MAY choose to use a widget that hides input values as they are typed for write-only fields. 

https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.4

Seeing as JSON Schema (and therefore OpenAPI v3.1) consider readOnly and writeOnly to be annotations only, the "application" can decide what to do with them. Prism as an application is choosing to strip them before passing them into JSON Schema specific tooling using our own helper logic. When the dependencies have a simple switch to do the same thing, we wont need to have our own logic to do the thing, but either way its basically the same.

2021-01-08 17:20 UTC, philsturgeon commented
@XVincentX misclick?

2021-01-08 17:23 UTC, XVincentX commented
Yeah — although the implementation is a no go anyway and will have to be refactored.

2021-01-12 12:05 UTC, philsturgeon commented
@XVincentX no worries, maybe we can leave this one up and somebody can take it over sometime?

2021-01-12 12:17 UTC, XVincentX commented
I do not mind keeping this open as a reminder!


> On 12 Jan 2021, at 13:06, Phil Sturgeon <notifications@github.com> wrote:
> 
> 
> @XVincentX no worries, maybe we can leave this one up and somebody can take it over sometime?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2021-07-08 08:33 UTC, radzserg commented
This issue has been addressed in https://github.com/stoplightio/prism/pull/1853

2021-07-08 08:33 UTC, closed without merging