fix #1895
stoplightio/prism pull request #2167
Opened 2022-11-02 10:17 UTC by nursanamar

Addresses #1895

**Summary**

**Checklist**

- The basics
  - [X] I tested these changes manually in my local or dev environment
- Tests
  - [X] N/A

2022-11-03 14:16 UTC, daniel-white commented on packages/core/src/factory.ts
> +      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
what typescript errors are these hiding? is there another way to express what you need this to?

2022-11-03 14:18 UTC, daniel-white commented on packages/http-server/src/getHttpConfigFromRequest.ts
> +export const getRequestPrefrences = (
also what is this doing other than adding an extra function?

2022-11-05 15:40 UTC, nursanamar commented
@daniel-white thank you for the reviews, about the test I don't really sure how to test this fix.

2022-11-06 12:42 UTC, nursanamar commented
Add some tests

2022-12-29 20:14 UTC, daniel-white requested changes

2022-12-29 20:14 UTC, daniel-white commented on packages/core/src/factory.ts
> +import { getHttpConfigFromRequest } from '@stoplight/prism-http-server/src/getHttpConfigFromRequest';
we do not want a circular dependency between core and http. could we change the call sites to `mockOrForward` to include calculation of the mocking config?

2022-12-29 20:14 UTC, daniel-white commented on packages/core/src/factory.ts
> +    const mockCall = () => {
in the event `mockOrForward`'s call sites include the mock config, this should be all reverted

2022-12-29 20:14 UTC, daniel-white commented on packages/core/src/factory.ts
> +        url: {
this also should support the `__prefer` query string options as well.

2023-05-17 17:06 UTC, closed without merging