Show unevaluated property name in error msg
stoplightio/prism pull request #2441
Opened 2023-12-20 07:29 UTC by aleung

**Summary**

This PR appends the property name to the message of `unevaluatedProperties` error.

Before, it's difficult to find out which property is unevaluated if the object schema has a long list of properties.
```
          {
            "location": [
              "response",
              "body",
              "context"
            ],
            "severity": "Error",
            "code": "unevaluatedProperties",
            "message": "Response body property context must NOT have unevaluated properties"
          },
```

After, the property name ('operation' in this example) is appended to the message.
```
          {
            "location": [
              "response",
              "body",
              "context"
            ],
            "severity": "Error",
            "code": "unevaluatedProperties",
            "message": "Response body property context must NOT have unevaluated properties: 'operation'"
          },
```

**Checklist**

- The basics
  - [x] I tested these changes manually in my local or dev environment
- Tests
  - [ ] Added or updated
  - [x] N/A
- Event Tracking
  - [ ] I added event tracking and followed the event tracking guidelines
  - [x] N/A
- Error Reporting
  - [ ] I reported errors and followed the error reporting guidelines
  - [x] N/A

2024-01-05 17:49 UTC, chohmann requested changes
@aleung This is great! Before we merge and release, could you add a unit test for this functionality?

2024-01-10 04:19 UTC, aleung commented
@chohmann Sure. Test case has been added.

2024-01-12 19:58 UTC, chohmann approved these changes

2024-01-12 19:59 UTC, merged

2024-01-12 20:21 UTC, chohmann commented
@aleung thank you for your contribution! This has been released in version 5.5.3 of Prism.