circular reference issue resolved
stoplightio/prism pull request #2538
Opened 2024-06-03 14:51 UTC by SB-rohitdesai

Mock server not working In case of circular references

**Summary**

Getting 500 Error or Sometimes might need to wait a long time before getting this error when spec having circular references
**Checklist**

- The basics
  - [X] I tested these changes manually in my local or dev environment
- Tests
  - [ ] Added or updated
  - [ ] N/A
- Event Tracking
  - [ ] I added event tracking and followed the event tracking guidelines
  - [ ] N/A
- Error Reporting
  - [ ] I reported errors and followed the error reporting guidelines
  - [ ] N/A

**Screenshots**

If applicable, add screenshots or gifs to help demonstrate the changes. If not applicable, remove this screenshots
section before creating the PR.

**Additional context**

Add any other context about the pull request here. Remove this section if there is no additional context.

2024-06-13 11:39 UTC, bhaskarsontakke approved these changes
looks good to me.

2024-06-21 14:09 UTC, brendarearden requested changes
could you add a test to cover the 500 scenario?

2024-06-21 14:42 UTC, brendarearden commented
is this supposed to include a version of json-schema-ref-parser that has your [optimization changes](https://github.com/stoplightio/json-schema-ref-parser/pull/62) in it? https://github.com/stoplightio/json-schema-ref-parser/pull/62 in it?

2024-06-24 15:24 UTC, SB-rohitdesai commented
> could you add a test to cover the 500 scenario?

Test case added

2024-06-24 15:25 UTC, SB-rohitdesai commented
> is this supposed to include a version of json-schema-ref-parser that has your [optimization changes](https://github.com/stoplightio/json-schema-ref-parser/pull/62) in it? [stoplightio/json-schema-ref-parser#62](https://github.com/stoplightio/json-schema-ref-parser/pull/62) in it?

Not required. currently we just merging this PR only

2024-06-24 15:37 UTC, bhaskarsontakke approved these changes

2024-06-24 15:41 UTC, bhaskarsontakke approved these changes

2024-06-24 16:48 UTC, brendarearden requested changes

2024-06-24 16:48 UTC, brendarearden commented on packages/http/src/mocker/__tests__/HttpMocker.spec.ts
> +    describe('should return 500 error', () => {
This test does not seem relevant to the PR that has been opened. Could you please add a test that covers the original circular reference problem and show that it is no longer throwing a 500?

2024-07-01 20:31 UTC, brendarearden commented on packages/http/src/mocker/__tests__/HttpMocker.spec.ts
> +    describe('With __bundled__ should get response', () => {
This test is passing with and without your changes so it still doesn't seem to be testing the initial bug you were seeing / the fix hasn't changed anything. It should be removed or changed to properly capture the issue you are seeing and fixing.

We have [test harness tests](https://github.com/stoplightio/prism/blob/master/test-harness/specs/references/E2E-Recursive-Object-Handling.oas3.txt) for circular references and those have been passing in the pipeline so it seems like circular references are getting resolved in most cases. Maybe a test harness test for the specific scenario that is causing you not to see circular references get resolved would help demonstrate the issue a bit better.

2024-07-08 13:34 UTC, closed without merging